site_name: GearVR Framework
site_description: Documentation for GearVR Framework
site_author: GearVR Framework Team

# Copyright
copyright: 'Copyright &copy; 2016 - 2017 Samsung'

repo_url: https://github.com/nitosan/GearVRf-docs
edit_uri: edit/master/docs/

theme: 'material'

extra_css:
  - 'stylesheets/extra.css'

google_analytics:
  - 'UA-105100670-1'
  - 'auto'

markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
  - pymdownx.magiclink
  - fontawesome_markdown

pages:
  - Home: index.md
  - Getting Started: getting_started.md
  - Tutorials:
    - Simple VR app: tutorials/simple_vr_app.md
    - Play With Materials: tutorials/play_with_material.md
    - Play With 3D Models: tutorials/play_with_3d_models.md
    - Play With Animation: tutorials/play_with_animation.md
    - Play With Controller: tutorials/play_with_controller.md
    - Play With VR Video: tutorials/play_with_vr_video.md
    - Play With Billboard: tutorials/play_with_billboard.md
    - Play With Component: tutorials/play_with_component.md
  - Programming Guide:
    - Overview: programming_guide/overview.md
    - Features:
      - Scene Graph: programming_guide/features/scene_graph.md
      - Rendering: programming_guide/features/rendering.md
      - Loading Assets: programming_guide/features/loading_assets.md
      - Render Data: programming_guide/features/render_data.md
      - Meshes: programming_guide/features/meshes.md
      - Materials: programming_guide/features/materials.md
      - Lighting: programming_guide/features/lighting.md
      - Phong Shader Template: programming_guide/features/phong_shader_template.md
      - Built-In Legacy Shader: programming_guide/features/builtin_legacy_shader.md
      - Picking: programming_guide/features/picking.md
    - Build Instructions: programming_guide/build_instructions.md
    - GearVRf Settings File: programming_guide/gearvr_settings_files.md
    - FAQ: programming_guide/faq.md
    - Video Tutorials: programming_guide/video_tutorials.md
    - Sample Code: programming_guide/sample_code.md
  - API Reference: api_reference.md
  - Community: community.md
  - Blog:
    - Blender Addon for GVRF: blog/blender_plugin_guide.md
    - GVRF and the X3D file format: blog/2017_4_17_x3d.md
  - About:
    - Contribution: about/contribution.md
    - Developer Certificate of Origin: about/certificate.md
    - Release Notes: about/release_notes.md
    - Roadmap: about/roadmap.md
    - License: about/license.md
    - Privacy Policy: about/privacy_policy.md
    - Terms of Service: about/terms_of_service.md
    - Marketing Resources: about/marketing_resource.md
    - Credits: about/credits.md